name: Deploy to Amazon EKS

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 1: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t flaskapp:v1 ./app

      # Step 2: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag flaskapp:v1 ${{ secrets.DOCKER_USERNAME }}/flaskapp:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/flaskapp:v1

      # Step 3: Set up AWS Credentials
      - name: Set up AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws configure set region ${{ secrets.AWS_REGION }}
     
      #create a cluster
      - name: Create Amazon EKS Cluster
        run: |
          aws eks create-cluster \
            --name cluster1 \
            --role-arn arn:aws:iam::339713099483:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS \
            --resources-vpc-config subnetIds=subnet-0aea3e3f83b5fad7c,subnet-0712019727fffb3fe \
            --region ${{ secrets.AWS_REGION }}
            
      # Step 4: Configure kubectl
      - name: Configure kubectl
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name cluster1

      # Step 5: Deploy Docker Image to EKS Cluster
      - name: Deploy to Amazon EKS
        run: |
          kubectl apply -f Deployment.yml
